// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {migration} from '../models';

export function CancelMigration():Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetConnectionHistory():Promise<Array<types.ConnectionConfig>>;

export function GetFunctions(arg1:string,arg2:string):Promise<Array<types.FunctionInfo>>;

export function GetMSSQLConnections():Promise<Array<types.ConnectionConfig>>;

export function GetMigrationHistory(arg1:number):Promise<Array<types.MigrationRecord>>;

export function GetMigrationLogs(arg1:string,arg2:number):Promise<Array<types.LogEntry>>;

export function GetMigrationStatus():Promise<migration.MigrationState>;

export function GetPostgresConnections():Promise<Array<types.ConnectionConfig>>;

export function GetStoredProcedures(arg1:string,arg2:string):Promise<Array<types.StoredProcedureInfo>>;

export function GetTableDetails(arg1:string,arg2:string,arg3:string,arg4:string):Promise<types.TableInfo>;

export function GetTables(arg1:string,arg2:string):Promise<Array<types.TableInfo>>;

export function GetViews(arg1:string,arg2:string):Promise<Array<types.ViewInfo>>;

export function PauseMigration():Promise<void>;

export function ResumeMigration():Promise<void>;

export function SaveConnection(arg1:types.ConnectionConfig):Promise<void>;

export function StartMigration(arg1:types.MigrationConfig,arg2:string):Promise<string>;

export function StartValidation(arg1:string,arg2:string,arg3:types.ValidationConfig):Promise<Array<types.ValidationResult>>;

export function TestMSSQLConnection(arg1:string):Promise<types.ConnectionTestResult>;

export function TestPostgresConnection(arg1:string):Promise<types.ConnectionTestResult>;
