// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelMigration() {
  return window['go']['main']['App']['CancelMigration']();
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteConnectionHistory(arg1) {
  return window['go']['main']['App']['DeleteConnectionHistory'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetConnectionHistories() {
  return window['go']['main']['App']['GetConnectionHistories']();
}

export function GetConnectionHistory() {
  return window['go']['main']['App']['GetConnectionHistory']();
}

export function GetFunctions(arg1, arg2) {
  return window['go']['main']['App']['GetFunctions'](arg1, arg2);
}

export function GetMSSQLConnections() {
  return window['go']['main']['App']['GetMSSQLConnections']();
}

export function GetMigrationHistory(arg1) {
  return window['go']['main']['App']['GetMigrationHistory'](arg1);
}

export function GetMigrationLogs(arg1, arg2) {
  return window['go']['main']['App']['GetMigrationLogs'](arg1, arg2);
}

export function GetMigrationStatus() {
  return window['go']['main']['App']['GetMigrationStatus']();
}

export function GetPostgresConnections() {
  return window['go']['main']['App']['GetPostgresConnections']();
}

export function GetStoredProcedures(arg1, arg2) {
  return window['go']['main']['App']['GetStoredProcedures'](arg1, arg2);
}

export function GetTableDetails(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetTableDetails'](arg1, arg2, arg3, arg4);
}

export function GetTables(arg1, arg2) {
  return window['go']['main']['App']['GetTables'](arg1, arg2);
}

export function GetViews(arg1, arg2) {
  return window['go']['main']['App']['GetViews'](arg1, arg2);
}

export function PauseMigration() {
  return window['go']['main']['App']['PauseMigration']();
}

export function ResumeMigration() {
  return window['go']['main']['App']['ResumeMigration']();
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SaveConnectionHistory(arg1) {
  return window['go']['main']['App']['SaveConnectionHistory'](arg1);
}

export function StartMigration(arg1, arg2) {
  return window['go']['main']['App']['StartMigration'](arg1, arg2);
}

export function StartValidation(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartValidation'](arg1, arg2, arg3);
}

export function TestMSSQLConnection(arg1) {
  return window['go']['main']['App']['TestMSSQLConnection'](arg1);
}

export function TestPostgresConnection(arg1) {
  return window['go']['main']['App']['TestPostgresConnection'](arg1);
}
